name: Deploy Spring Boot to EC2

on:
  push:
    branches: '*'  # main 브랜치 push 시 작동

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Upload JAR to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "build/libs/*.jar"
        target: "/home/${{ secrets.EC2_USER }}/githubaction"

    - name: Run JAR on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          pkill -f 'java -jar' || true
          export TMDB_API_KEY="e3916729ef63dc298f12e1d904a72fcd"
          export JWT_KEY_KEY1="SpringSecurityJWTPracticeProjectIsSoGoodAndThisProjectIsSoFunSpringSecurityJWTPracticeProjectIsSoGoodAndThisProjectIsSoFun"
          export JWT_KEY_KEY2="GoodSpringSecurityNiceSpringSecurityGoodSpringSecurityNiceSpringSecurityGoodSpringSecurityNiceSpringSecurityGoodSpringSecurityNiceSpringSecurity"
          export JWT_KEY_KEY3="HelloSpringSecurityHelloSpringSecurityHelloSpringSecurityHelloSpringSecurityHelloSpringSecurityHelloSpringSecurityHelloSpringSecurityHelloSpringSecurity"
          export DB_URL=jdbc:mysql://ec2-54-180-122-233.ap-northeast-2.compute.amazonaws.com:3306/movie_review
          export DB_USERNAME=db
          export DB_PASSWORD=fastcampus
          nohup java -jar /home/${{ secrets.EC2_USER }}/githubaction/build/libs/cineView-0.0.1-SNAPSHOT.jar > /home/${{ secrets.EC2_USER }}/githubaction/build/libs/server.log 2>&1 &
